- .stylish-haskell.yaml
- .travis.yml
- CHANGELOG.md
- issue-wanted.cabal
- src/Prelude.hs
- stack.yaml
Resolves [#7](https://github.com/kowainik/issue-wanted/issues/7)
> [#7] Fix env and add relude

- .travis.yml
- issue-wanted.cabal
- stack.yaml
In order to completely resolve issue #25, I also need to update the `travis.yml` file but I'm not sure how to go about this. The `three-layer` example repository seems to use `circleci`, so I can't really use it as a reference. Should we use circle-ci instead? Any suggestions?
> [#25] Update cabal and stack.yaml files

- README.md
> [#32] Update README.md

- README.md
> [#51] Add instructions for testing database

- src/IW/Db/Issue.hs
> [#59] Update SQL query functions for Issue type

- sql/schema.sql
- sql/seed.sql
- src/IW/Core/Issue.hs
> [#70] Change name of owner column in issues table

- sql/schema.sql
- sql/seed.sql
- src/IW/Core/Issue.hs
- src/IW/Core/Repo.hs
> [#76] Change fields in Issue record

- sql/schema.sql
- sql/seed.sql
- src/IW/Core/Issue.hs
- src/IW/Core/Repo.hs
- src/IW/Db/Issue.hs
> [#78] Update Issue SQL schema

- sql/drop.sql
- sql/schema.sql
I believe this is what we want. Not sure if we should use `WITHOUT TIME ZONE` or `WITH TIME ZONE`. Went with the latter just to be safe.
> [#73] Add created_at and updated_at columns

- issue-wanted.cabal
- sql/schema.sql
- src/IW/Core/Issue.hs
- src/IW/Db/Issue.hs
- stack.yaml
- test/Spec.hs
- test/Test/Assert.hs
- test/Test/Common.hs
- test/Test/Core/Issue.hs
- test/Test/Core/Repo.hs
- test/Test/Db.hs
> [#74] Setup round-trip property testing for DB

- issue-wanted.cabal
- sql/seed.sql
- src/IW/Db.hs
- src/IW/Db/Functions.hs
- src/IW/Db/Repo.hs
- src/IW/Db/Schema.hs
- src/Prelude.hs
- test/Spec.hs
- test/Test/Assert.hs
- test/Test/Common.hs
- test/Test/Data.hs
- test/Test/Db.hs
> [#85] Add unit tests for DB functions

- issue-wanted.cabal
- src/IW/Core/Issue.hs
- src/IW/Core/Repo.hs
- src/IW/Core/WithId.hs
- src/IW/Db/Issue.hs
- src/IW/Db/Repo.hs
- src/IW/Server/Issue.hs
- test/Test/Core/Issue.hs
- test/Test/Core/Repo.hs
- test/Test/Data.hs
- test/Test/Db.hs
- test/Test/Gen.hs
Resolves #89
My first attempt at implementing the `WithId` type. I'm still confused as to how to use `(:.)` to derive the `ToRow` and `FromRow` instances of `WithId`. I used `(<$>)` and `(<*>):
```
instance FromRow a => FromRow (WithId a) where
fromRow = WithId <$> field <*> fromRow
instance ToRow a => ToRow (WithId a) where
toRow WithId{..} = toRow withIdVal  
```
Another thing is the test with `WithId Issue`:
```
issueViaSql :: (WithDb env m, WithError m) => WithId Issue -> m (WithId Issue)
issueViaSql WithId{..} = asSingleRow $ query
[sql| SELECT ?, ?, ?, ?, ?, ?, (? :: TEXT ARRAY) |]
(Only (issueId issue) :. issue)
((Only withIdId) :. withIdVal)
```
I'm still using `(:.)` which is not what I want, but if I don't I get a format error saying I don't have enough parameters.
> [#89] Implement WithId type

- src/IW/Core/Repo.hs
- src/IW/Db/Issue.hs
- src/IW/Db/Repo.hs
Resolves #62
Depends on PR #69
> [#62] Implement database related functions for Repo type

- src/IW/Core/Issue.hs
- src/IW/Core/Repo.hs
- src/IW/Core/SqlArray.hs
- test/Test/Core/Issue.hs
- test/Test/Core/Repo.hs
- test/Test/Data.hs
> [#93] Introduce Category/Label newtypes

- src/IW/Db/Issue.hs
- src/IW/Db/Repo.hs
> [#97] Add LIMIT 100 to DB query functions

- issue-wanted.cabal
- src/IW/Core/Id.hs
- src/IW/Core/Issue.hs
- src/IW/Core/Repo.hs
- src/IW/Core/SqlArray.hs
- src/IW/Core/Url.hs
- src/IW/Sync/Search.hs
> [#107] Add Url newtype for wrapping URL text

- issue-wanted.cabal
- src/IW.hs
- src/IW/App/Env.hs
- src/IW/Effects/Download.hs
- test/Spec.hs
- test/Test/Sync.hs
> [#105] Implement `MonadDownload` effect

- src/IW/Db/Issue.hs
- src/IW/Db/Repo.hs
- src/IW/Server/Issue.hs
- src/Prelude.hs
- stack.yaml
- test/Test/Data.hs
- test/Test/Db.hs
> [#92] Implement better DB filter functions along with their tests

- issue-wanted.cabal
- src/IW/App/Error.hs
- src/IW/App/Monad.hs
- src/IW/Db/Repo.hs
- src/IW/Effects/Cabal.hs
- src/IW/Effects/Download.hs
- src/IW/Sync/Search.hs
- src/IW/Sync/Update.hs
- src/Prelude.hs
- stack.yaml
- test/Test/Sync.hs
> [#104] Add functionality for associating repos with their categories

- src/IW/App/Error.hs
- src/IW/Db/Functions.hs
- src/IW/Effects/Download.hs
- test/Test/Sync.hs
> [#110] Remove Internal/External error wrappers used for AppErrorType

- src/IW/App/Error.hs
- src/IW/Sync/Search.hs
- test/Test/Sync.hs
> [#99] Add logging and error handling to `parseUserData` function

- issue-wanted.cabal
- src/IW.hs
- src/IW/Core/Repo.hs
- src/IW/Db/Issue.hs
- src/IW/Db/Repo.hs
- src/IW/Server.hs
- src/IW/Server/Issue.hs
- src/IW/Server/Repo.hs
- test/Test/Db.hs
> [#114] Implement proper pagination

- README.md
- frontend/.gitignore
- frontend/elm.json
- frontend/elmapp.config.js
- frontend/public/index.html
- frontend/public/manifest.json
- frontend/src/IW/Api.elm
- frontend/src/IW/Core/Decoder.elm
- frontend/src/IW/Core/ElmStreet.elm
- frontend/src/IW/Core/Encoder.elm
- frontend/src/IW/Core/Types.elm
- frontend/src/Main.elm
- frontend/src/index.js
- frontend/src/main.css
- frontend/src/registerServiceWorker.js
- generate-elm/Main.hs
- issue-wanted.cabal
- src/IW/Core/Issue.hs
- src/IW/Core/Repo.hs
- src/IW/Core/SqlArray.hs
- src/Prelude.hs
- stack.yaml
Resolves #111
Try to run it and let me know if everything works for you, or some instructions are not clear. Also, point out to the places I should explain in details. I would be happy to help with it! 
I will wire up some endpoint in a separate PR to ease the amount of info to proceed with.
> [#111] Scaffold initial frontend

- sql/schema.sql
- src/IW/Core/Issue.hs
- src/IW/Core/Repo.hs
- src/IW/Core/Url.hs
- src/IW/Db/Repo.hs
- src/IW/Effects/Cabal.hs
- src/IW/Sync/Search.hs
- src/IW/Sync/Update.hs
- test/Test/Core/Repo.hs
- test/Test/Data.hs
- test/Test/Sync.hs
> [#120] Add repoCabalUrl field to Repo type

- .circleci/config.yml
> [#141] Add frontend check to CI

- src/IW/App/Error.hs
- src/IW/Core/Repo.hs
- src/IW/Effects/Cabal.hs
- src/IW/Effects/Download.hs
- test/Test/Sync.hs
> [#102] Add handling of cabal file parse errors

- README.md
> [#122] Update README
